// angular-todo/src/app/app.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  generateTasks,
  measure,
  formatResults,
  downloadResultsAsJSON,
  Task,
  BenchResult,
} from './benchmark';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  readonly PRIORITIES = ['Basse', 'Moyenne', 'Haute'];

  tasks = signal<Task[]>([]);
  name = '';
  priority = 'Moyenne';
  editingId: number | null = null;
  editName = '';
  editPriority = 'Moyenne';
  benchResults = signal<BenchResult[]>([]);
  running = signal(false);
  private idCounter = 0;

  addTask(): void {
    if (!this.name.trim()) return;
    this.tasks.update((prev) => [
      ...prev,
      { id: this.idCounter++, name: this.name.trim(), priority: this.priority },
    ]);
    this.name = '';
    this.priority = 'Moyenne';
  }

  removeTask(id: number): void {
    this.tasks.update((prev) => prev.filter((t) => t.id !== id));
  }

  startEdit(task: Task): void {
    this.editingId = task.id;
    this.editName = task.name;
    this.editPriority = task.priority;
  }

  saveEdit(id: number): void {
    this.tasks.update((prev) =>
      prev.map((t) =>
        t.id === id ? { ...t, name: this.editName, priority: this.editPriority } : t
      )
    );
    this.editingId = null;
  }

  cancelEdit(): void {
    this.editingId = null;
  }

  formatResults(results: BenchResult[]): string {
    return formatResults(results);
  }

  download(): void {
    downloadResultsAsJSON('angular', this.benchResults());
  }

  // ---- Benchmark ----
  // Angular utilise la détection de changement (zone.js ou signals) ;
  // on attend une micro-tâche pour laisser le moteur de rendu patcher le DOM.
  async runBenchmark(): Promise<void> {
    this.running.set(true);
    const results: BenchResult[] = [];

    for (const count of [100, 500, 1000]) {
      const fresh = generateTasks(count, this.idCounter);
      this.idCounter += count;
      const r = await measure(`Rendu initial (${count} tâches)`, async () => {
        this.tasks.set(fresh);
        await new Promise((resolve) => setTimeout(resolve, 0));
      });
      results.push(r);
    }

    const updateR = await measure('Mise à jour de 50 tâches', async () => {
      this.tasks.update((prev) =>
        prev.map((t, i) => (i < 50 ? { ...t, name: t.name + ' (modifié)' } : t))
      );
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
    results.push(updateR);

    const deleteR = await measure('Suppression de 50 tâches', async () => {
      this.tasks.update((prev) => prev.slice(50));
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
    results.push(deleteR);

    this.benchResults.set(results);
    this.running.set(false);
  }
}

<div class="app">
  <h1>📝 To-Do List — Angular</h1>

  <form class="task-form" (ngSubmit)="addTask()">
    <input type="text" placeholder="Nom de la tâche" [(ngModel)]="name" name="name" />
    <select [(ngModel)]="priority" name="priority">
      <option *ngFor="let p of PRIORITIES" [value]="p">{{ p }}</option>
    </select>
    <button type="submit">Ajouter</button>
  </form>

  <div class="bench-panel">
    <button (click)="runBenchmark()" [disabled]="running()">
      {{ running() ? 'Benchmark en cours…' : '▶ Lancer le benchmark' }}
    </button>
    <ng-container *ngIf="benchResults().length > 0">
      <pre>{{ formatResults(benchResults()) }}</pre>
      <button (click)="download()">💾 Télécharger les résultats (JSON)</button>
    </ng-container>
  </div>

  <p class="task-count">{{ tasks().length }} tâche(s)</p>

  <ul class="task-list">
    <li *ngFor="let task of tasks()" [ngClass]="'priority-' + task.priority">
      <ng-container *ngIf="editingId === task.id; else viewMode">
        <input [(ngModel)]="editName" name="editName" />
        <select [(ngModel)]="editPriority" name="editPriority">
          <option *ngFor="let p of PRIORITIES" [value]="p">{{ p }}</option>
        </select>
        <button (click)="saveEdit(task.id)">✔ Enregistrer</button>
        <button (click)="cancelEdit()">✖ Annuler</button>
      </ng-container>
      <ng-template #viewMode>
        <span class="task-name">{{ task.name }}</span>
        <span class="task-priority">{{ task.priority }}</span>
        <button (click)="startEdit(task)">✎ Modifier</button>
        <button (click)="removeTask(task.id)">🗑 Supprimer</button>
      </ng-template>
    </li>
  </ul>
</div>

// react-todo/src/App.jsx
import { useState, useRef } from 'react';
import './App.css';
import { generateTasks, measure, formatResults, downloadResultsAsJSON } from './benchmark';

const PRIORITIES = ['Basse', 'Moyenne', 'Haute'];

function App() {
  const [tasks, setTasks] = useState([]);
  const [name, setName] = useState('');
  const [priority, setPriority] = useState('Moyenne');
  const [editingId, setEditingId] = useState(null);
  const [editName, setEditName] = useState('');
  const [editPriority, setEditPriority] = useState('Moyenne');
  const [benchResults, setBenchResults] = useState([]);
  const [running, setRunning] = useState(false);
  const idCounter = useRef(0);

  function addTask(e) {
    e.preventDefault();
    if (!name.trim()) return;
    setTasks((prev) => [
      ...prev,
      { id: idCounter.current++, name: name.trim(), priority },
    ]);
    setName('');
    setPriority('Moyenne');
  }

  function removeTask(id) {
    setTasks((prev) => prev.filter((t) => t.id !== id));
  }

  function startEdit(task) {
    setEditingId(task.id);
    setEditName(task.name);
    setEditPriority(task.priority);
  }

  function saveEdit(id) {
    setTasks((prev) =>
      prev.map((t) =>
        t.id === id ? { ...t, name: editName, priority: editPriority } : t
      )
    );
    setEditingId(null);
  }

  // ---- Benchmark ----
  async function runBenchmark() {
    setRunning(true);
    const results = [];

    // Rendu initial : 100, 500, 1000 tâches
    for (const count of [100, 500, 1000]) {
      const fresh = generateTasks(count, idCounter.current);
      idCounter.current += count;
      const r = await measure(`Rendu initial (${count} tâches)`, () => {
        return new Promise((resolve) => {
          setTasks(fresh);
          setTimeout(resolve, 0);
        });
      });
      results.push(r);
    }

    // Mise à jour de 50 tâches
    const updateR = await measure('Mise à jour de 50 tâches', () => {
      return new Promise((resolve) => {
        setTasks((prev) =>
          prev.map((t, i) =>
            i < 50 ? { ...t, name: t.name + ' (modifié)' } : t
          )
        );
        setTimeout(resolve, 0);
      });
    });
    results.push(updateR);

    // Suppression de 50 tâches
    const deleteR = await measure('Suppression de 50 tâches', () => {
      return new Promise((resolve) => {
        setTasks((prev) => prev.slice(50));
        setTimeout(resolve, 0);
      });
    });
    results.push(deleteR);

    setBenchResults(results);
    setRunning(false);
  }

  return (
    <div className="app">
      <h1>📝 To-Do List — React</h1>

      <form onSubmit={addTask} className="task-form">
        <input
          type="text"
          placeholder="Nom de la tâche"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <select value={priority} onChange={(e) => setPriority(e.target.value)}>
          {PRIORITIES.map((p) => (
            <option key={p} value={p}>{p}</option>
          ))}
        </select>
        <button type="submit">Ajouter</button>
      </form>

      <div className="bench-panel">
        <button onClick={runBenchmark} disabled={running}>
          {running ? 'Benchmark en cours…' : '▶ Lancer le benchmark'}
        </button>
        {benchResults.length > 0 && (
          <>
            <pre>{formatResults(benchResults)}</pre>
            <button onClick={() => downloadResultsAsJSON('react', benchResults)}>
              💾 Télécharger les résultats (JSON)
            </button>
          </>
        )}
      </div>

      <p className="task-count">{tasks.length} tâche(s)</p>

      <ul className="task-list">
        {tasks.map((task) => (
          <li key={task.id} className={`priority-${task.priority}`}>
            {editingId === task.id ? (
              <>
                <input
                  value={editName}
                  onChange={(e) => setEditName(e.target.value)}
                />
                <select
                  value={editPriority}
                  onChange={(e) => setEditPriority(e.target.value)}
                >
                  {PRIORITIES.map((p) => (
                    <option key={p} value={p}>{p}</option>
                  ))}
                </select>
                <button onClick={() => saveEdit(task.id)}>✔ Enregistrer</button>
                <button onClick={() => setEditingId(null)}>✖ Annuler</button>
              </>
            ) : (
              <>
                <span className="task-name">{task.name}</span>
                <span className="task-priority">{task.priority}</span>
                <button onClick={() => startEdit(task)}>✎ Modifier</button>
                <button onClick={() => removeTask(task.id)}>🗑 Supprimer</button>
              </>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;
